### ISSUE TITLE
TP ended

### ISSUE THREAD

**Issue by LoicDelorme** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-2-delorme-kasprzyk#1]
:)

**Comment by Slashgear** [comment]
Alors franchement c'est pas mal, le rapport est très bien, l'uml est clair. Vous semblez avoir très bien compris ce design pattern.

Je n'ai qu'un seul bémol.
Dans vos Visiteurs vous avez fait le choix de renvoyer des Optional<Integer>.
C'est une bonne idée 😄 

Mais parfois cette valeur de retour ne semble pas avoir de sens et c'est étrange.

De plus appeler un `get`sur un Optional sans avoir fait de ìsPresent()`avant, c'est dangereux. Vous risquer une NoSuchElementException ([doc](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#get--)

Regarder un peu la doc Optional et les différentes méthodes disponible. Vous verrez qu'il est possible de les traiter de manière fonctionnelle.

**Comment by LoicDelorme** [comment]
Merci pour vos retours. Nous avons corrigé les éléments mentionnés. Après reflexion, nous avons décidé d'introduire une deuxième interface qui s'apparente au pattern visiteur dans le but de respecter le principe SOLID et pour permettre de retourner des valeurs proprement que lorsque cela est nécessaire.

Peut-on clore l'issue ?

**Comment by Slashgear** [comment]
C'est très très bien 👍
